services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: luxor
      POSTGRES_PASSWORD: development
      POSTGRES_DB: test-db
    container_name: db
    volumes:
      # - ./database:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: luxor@fake.com
      PGADMIN_DEFAULT_PASSWORD: development
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - 54322:80

# volumes:
#   database: