name: Automatic deployment to Digital Ocean

on: 
  push:
    branches:
      - main

jobs:
  deployment-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: pulling latest changes from host machine
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/lucas/kingfisher
            git pull

      - name: build frontend for production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/lucas/kingfisher/backend
            npm run build
            echo ${{secrets.PASSWORD}}
            sudo -S rm -rf /var/www/kingfisher/html
            sudo mkdir /var/www/kingfisher/html
            sudo cp -r ./dist/* /var/www/kingfisher/html/
                
            