name: Automatic deployment to Digital Ocean

on: 
  push:
    branches:
      - main

jobs:
  deployment-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: pulling latest changes from host machine
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/lucas/kingfisher
            git pull

      - name: build frontend for production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/lucas/kingfisher/frontend
            bash build-frontend.sh ${{secrets.PASSWORD}}

      - name: email success notification
        if: ${{success()}}
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address if not connection_url:
          server_address: smtp-mail.outlook.com
          # Server port, default 25:
          server_port: 587
          # Optional whether this connection use TLS (default is true if server_port is 465):
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: ${{secrets.MAIL_USERNAME}}
          # Required sender full name (address can be skipped):
          from: Kigfisher workflow # <user@example.com>
          # Optional plain body:
          body: 🎆 Build job of ${{github.repository}} completed successfully! ✨
          
                
            