name: Automatic deployment to Digital Ocean

on: 
  push:
    branches:
      - main

jobs:
  deployment-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/lucas/kingfisher
            git pull